### ISSUE TITLE
Missing files in sdist

### ISSUE THREAD

**Issue by thatch** [sefiit/rvgeocoder#8]
It appears that the manifest is missing at least one file necessary to build
from the sdist for version 1.0.7. You're in good company, about 5% of other
projects updated in the last year are also missing files.

```
+ /tmp/venv/bin/pip3 wheel --no-binary rvgeocoder -w /tmp/ext rvgeocoder==1.0.7
Looking in indexes: http://10.10.0.139:9191/root/pypi/+simple/
Collecting rvgeocoder==1.0.7
  Downloading http://10.10.0.139:9191/root/pypi/%2Bf/3c5/1f3288f2c4279/rvgeocoder-1.0.7.tar.gz (2.2 MB)
    ERROR: Command errored out with exit status 1:
     command: /tmp/venv/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-wheel-h_je532c/rvgeocoder/setup.py'"'"'; __file__='"'"'/tmp/pip-wheel-h_je532c/rvgeocoder/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-wheel-h_je532c/rvgeocoder/pip-egg-info
         cwd: /tmp/pip-wheel-h_je532c/rvgeocoder/
    Complete output (7 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-wheel-h_je532c/rvgeocoder/setup.py", line 32, in <module>
        long_description=read('longdesc.txt'))
      File "/tmp/pip-wheel-h_je532c/rvgeocoder/setup.py", line 8, in read
        return open(os.path.join(os.path.dirname(__file__), filename)).read()
    FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pip-wheel-h_je532c/rvgeocoder/longdesc.txt'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

**Comment by sefitz** [comment]
resolved in 1.0.8.
